filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" plugins go here
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-scripts/indentpython.vim'
Bundle 'Valloric/YouCompleteMe'
Plugin 'ternjs/tern_for_vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'pearofducks/ansible-vim'
Plugin 'mileszs/ack.vim'
Plugin 'othree/html5.vim'
Plugin 'othree/yajs.vim'
Plugin 'rdolgushin/groovy.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'nightsense/simplifysimplify'
Bundle 'vim-scripts/groovyindent.git'

call vundle#end()

filetype indent plugin on
let python_highlight_all=1
syntax on

fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd FileType c,cpp,java,php,ruby,python,javascript,groovy autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()
autocmd FileType python nmap <F5> :w !python %<cr>

set regexpengine=1
set laststatus=2
set backspace=2
set encoding=utf-8
set number
set autoindent
set fileformat=unix
set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4
set hlsearch
set ttyfast
if !has('nvim')
    set ttyscroll=999
endif
set ruler
set history=128
set undolevels=128
set ignorecase
set smartcase
set incsearch
set showmatch

let g:airline_powerline_fonts = 1

nnoremap <up> <C-w>k
nnoremap <down> <C-w>j
nnoremap <left> <C-w>h
nnoremap <right> <C-w>l
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
vnoremap . :normal .<CR>

let hlstate=0
nnoremap ,h :if (hlstate == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=1-hlstate<cr>

let g:ycm_autoclose_preview_window_after_completion=1

" NERDTree
map ,t :NERDTreeToggle<CR>

" CTRLP
nmap ,b :CtrlPBuffer<CR>
nmap ,f :CtrlP<CR>

" syntastic
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open=1
let g:syntastic_check_on_wq=0
let g:syntastic_python_checkers=['flake8']
let g:syntastic_aggregate_errors=1
let g:syntastic_javascript_checkers=['eslint']
if executable('node_modules/.bin/eslint')
    let g:syntastic_javascript_eslint_exec = 'node_modules/.bin/eslint'
endif

if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
  let g:ackprg = 'ag --vimgrep --smart-case'
  cnoreabbrev ag Ack
  cnoreabbrev aG Ack
  cnoreabbrev Ag Ack
  cnoreabbrev AG Ack
endif

let g:ctrlp_working_path_mode='a'

set wildignore+=*.swp,*.zip,*.tar.gz,*.pyc,*.so,*.dll,*.exe
let NERDTreeIgnore=['\.pyc$','\.swp$']

if has("gui_running")
	set guioptions-=m
	set guioptions-=T
	set guioptions-=r
	set guioptions-=L
	set guifont=Monaco\ for\ Powerline\ 10
    colorscheme simplifysimplify-dark
else
    set t_Co=256
    colorscheme molokai
endif

"" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
